SHow and hide mobile menu added
Oscar-Espinoza/Portfolio-page pull request #10
Opened 2022-11-14 19:28 UTC by Oscar-Espinoza

In this commit, I added the functionality for the menu to appear and disappear when you click on the toggle button or the close menu button

2022-11-14 20:51 UTC, sja-thedude requested changes
## Invalid Code Review Request ❌

Hi @Oscar-Espinoza, This is @sja-thedude your code reviewer.

While you made a great effort in this project, I cannot proceed to review your code.

You have submitted a project, that is a pair programming project and doesn't have commits from both partners. Also, all linters are not passing, just disable linter to fix it.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-11-14 23:02 UTC, Ugboaja-Uchechi requested changes
Hi @Oscar-Espinoza, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- Linters are passing ✔️ 
- README is descriptive 👍 
- I love the last commit message 👏 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-14 23:02 UTC, Ugboaja-Uchechi commented on app.js
> +  });
- [ ] Great job with your design and functionalities 👏 . As stated in the project requirements, kindly make sure when a user clicks any of the mobile menu options, the correct part of the page is displayed. 🙏 
- [ ] As stated in the project requirements, kindly make sure when a user clicks any of the mobile menu options, the mobile menu disappears. 🙏

2022-11-15 15:25 UTC, Olamarx approved these changes
Hi @Oscar-Espinoza, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media2.giphy.com/media/3oz8xVjxTPNEzyKRKU/giphy.gif"/>
## Highlights
- All linters passed ✔️ 
- Mobile menu functionalities ✅ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-15 15:50 UTC, merged